[parity]
# Ropsten PoW Test Network
chain = "ropsten"
base_path = "/primas/parity/data"

[ui]
# You will need to unlock accounts manually if Wallet is disabled.
disable = true

[websockets]
# UI won't work and WebSockets server will be not available.
disable = false
port = 8546
interface = "all"
origins = ["all"]
apis = ["web3", "eth", "net", "rpc", "pubsub"]
hosts = ["all"]

[dapps]
# You won't be able to access any web Dapps.
disable = true

[rpc]
#  JSON-RPC will be listening for connections on IP 0.0.0.0.
interface = "127.0.0.1"
# Allows Cross-Origin Requests from domain '*'.
cors = "*"
