version: '2'
services:
  primas_parity:
    image: "parity/parity:v1.8.4"
    ports:
     - "8545:8545"
     - "8546:8546"
    volumes:
     - .:/primas/parity
    command: --config /primas/parity/config.toml
    container_name: primas_parity